# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormReports(object):
    def setupUi(self, FormReports):
        FormReports.setObjectName("FormReports")
        FormReports.resize(650, 450)
        FormReports.setMaximumSize(QtCore.QSize(650, 450))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/aelmac_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormReports.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FormReports)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 631, 101))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.txt_filter = QtWidgets.QLineEdit(self.groupBox)
        self.txt_filter.setGeometry(QtCore.QRect(20, 45, 361, 32))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setWeight(50)
        self.txt_filter.setFont(font)
        self.txt_filter.setObjectName("txt_filter")
        self.cmb_filter = QtWidgets.QComboBox(self.groupBox)
        self.cmb_filter.setGeometry(QtCore.QRect(406, 45, 201, 32))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setWeight(50)
        self.cmb_filter.setFont(font)
        self.cmb_filter.setObjectName("cmb_filter")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.cmb_filter.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 631, 281))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tb_results = QtWidgets.QTableWidget(self.groupBox_2)
        self.tb_results.setGeometry(QtCore.QRect(10, 30, 611, 241))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tb_results.setFont(font)
        self.tb_results.setObjectName("tb_results")
        self.btn_export = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export.setGeometry(QtCore.QRect(10, 410, 631, 34))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(True)
        font.setWeight(75)
        self.btn_export.setFont(font)
        self.btn_export.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/page_excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_export.setIcon(icon1)
        self.btn_export.setObjectName("btn_export")
        FormReports.setCentralWidget(self.centralwidget)

        self.retranslateUi(FormReports)
        QtCore.QMetaObject.connectSlotsByName(FormReports)

    def retranslateUi(self, FormReports):
        _translate = QtCore.QCoreApplication.translate
        FormReports.setWindowTitle(_translate("FormReports", "GERENCIADOR DE RELATÓRIOS"))
        self.groupBox.setTitle(_translate("FormReports", "FILTRO"))
        self.cmb_filter.setItemText(0, _translate("FormReports", "Nome"))
        self.cmb_filter.setItemText(1, _translate("FormReports", "Data de Nascimento"))
        self.cmb_filter.setItemText(2, _translate("FormReports", "Telefone (Celular)"))
        self.cmb_filter.setItemText(3, _translate("FormReports", "Telefone (Residencial)"))
        self.cmb_filter.setItemText(4, _translate("FormReports", "Gênero"))
        self.cmb_filter.setItemText(5, _translate("FormReports", "Endereço"))
        self.cmb_filter.setItemText(6, _translate("FormReports", "Bairro"))
        self.cmb_filter.setItemText(7, _translate("FormReports", "Cidade"))
        self.cmb_filter.setItemText(8, _translate("FormReports", "Tratamento: HL"))
        self.cmb_filter.setItemText(9, _translate("FormReports", "Tratamento: P1/2"))
        self.cmb_filter.setItemText(10, _translate("FormReports", "Tratamento: P3E"))
        self.cmb_filter.setItemText(11, _translate("FormReports", "Tratamento: P3F"))
        self.groupBox_2.setTitle(_translate("FormReports", "RESULTADOS"))
        self.btn_export.setText(_translate("FormReports", "EXPORTAR RESULTADOS PARA EXCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormReports = QtWidgets.QMainWindow()
    ui = Ui_FormReports()
    ui.setupUi(FormReports)
    FormReports.show()
    sys.exit(app.exec_())
